apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80  # พอร์ตที่ Service เปิดใช้งาน
      targetPort: 80  # พอร์ตที่รับจาก Container
      nodePort: 30181
