apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: apache.example.com  # ระบุชื่อโดเมนที่ต้องการใช้สำหรับ Ingress
      http:
        paths:
          - path: /apache-app
            pathType: Prefix
            backend:
              service:
                name: apache-service  # ชื่อของ Service ที่ต้องการเชื่อมต่อ
                port:
                  number: 80  # พอร์ตของ Service
